# Generated by Django 3.1.2 on 2020-10-25 11:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TutorialsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorial_category', models.CharField(max_length=255)),
                ('tutorial_summary', models.CharField(max_length=255)),
                ('tutorial_link', models.CharField(max_length=255)),
                ('tutorial_image', models.URLField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='TutorialSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorial_series', models.CharField(max_length=255)),
                ('tutorial_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.tutorialscategory', verbose_name='Category')),
            ],
            options={
                'verbose_name_plural': 'Series',
            },
        ),
        migrations.CreateModel(
            name='Tutorials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorial_title', models.CharField(max_length=255)),
                ('tutorial_content', models.TextField()),
                ('tutorial_published_date', models.DateTimeField(default=datetime.datetime(2020, 10, 25, 12, 56, 49, 803718), verbose_name='Date Published')),
                ('tutorial_image_desc', models.URLField(max_length=255)),
                ('tutorial_link', models.URLField(default=1, max_length=255)),
                ('tutorial_series', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.tutorialseries', verbose_name='Series')),
            ],
            options={
                'verbose_name_plural': 'Tutorials',
            },
        ),
    ]
