# Generated by Django 3.1.2 on 2020-10-25 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorialseries',
            name='series_summary',
            field=models.CharField(default=1, max_length=255),
        ),
        migrations.AlterField(
            model_name='tutorials',
            name='tutorial_published_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 25, 13, 27, 23, 689602), verbose_name='Date Published'),
        ),
    ]
