# Generated by Django 3.1.2 on 2020-10-25 12:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201025_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorialscategory',
            name='tutorial_image',
        ),
        migrations.AlterField(
            model_name='tutorials',
            name='tutorial_published_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 25, 13, 31, 11, 324756), verbose_name='Date Published'),
        ),
    ]
