# Generated by Django 3.1.2 on 2020-10-25 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201025_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorialscategory',
            old_name='tutorial_link',
            new_name='category_link',
        ),
        migrations.AlterField(
            model_name='tutorials',
            name='tutorial_published_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 25, 13, 33, 28, 760759), verbose_name='Date Published'),
        ),
    ]
