# Generated by Django 3.1.2 on 2020-10-25 12:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201025_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorials',
            name='tutorial_link',
            field=models.CharField(default=1, max_length=255),
        ),
        migrations.AlterField(
            model_name='tutorials',
            name='tutorial_published_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 25, 13, 49, 25, 58522), verbose_name='Date Published'),
        ),
    ]
