# Generated by Django 3.1.2 on 2020-10-25 17:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201025_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorials',
            name='tutorial_published_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 25, 18, 29, 37, 839274), verbose_name='Date Published'),
        ),
    ]
